Wait while reloading

diff --git a/cookbooks/unicorn/templates/default/unicorn_init_d.erb b/cookbooks/unicorn/templates/default/unicorn_init_d.erb
--- a/cookbooks/unicorn/templates/default/unicorn_init_d.erb
+++ b/cookbooks/unicorn/templates/default/unicorn_init_d.erb
@@ -52,11 +52,34 @@ kill_unicorn() {
 	fi
 }
 
-case "$1" in
-   start)
+start_unicorn() {
 	echo -n "Starting $NAME: "
 	$START_STOP_DAEMON -c $USER --start --exec $DAEMON -p $PID_FILE -- -c "$CMD" || exit 1
 	echo "$NAME."
+}
+
+reload_unicorn() {
+	echo -n "Reloading $DESC: "
+	old_pid=$(cat $PID_FILE)
+	kill_unicorn "-USR2"
+	i=0
+  while [ true ]; do
+    sleep 2
+    i=$(expr $i + 1)
+    if [ "$(cat $PID_FILE)" != "$old_pid" -a ! -f $PID_FILE.oldbin ]; then
+    	echo "$NAME."
+    	break
+    fi
+    if [ $i -gt 60 ]; then
+      echo "Unable to find running process after 60 seconds."
+      exit 1
+    fi
+  done
+}
+
+case "$1" in
+  start)
+  	start_unicorn
 	;;
   stop)
 	echo -n "Stopping $NAME: "
@@ -64,9 +87,11 @@ case "$1" in
 	echo "$NAME."
 	;;
   reload)
-	echo -n "Graceful restarting $DESC: "
-	kill_unicorn "-USR2"
-	echo "$NAME."
+  if [ -f $PID_FILE ] && [ -d "/proc/$(cat $PID_FILE)" ]; then
+  	reload_unicorn
+  else
+  	start_unicorn
+	fi
 	;;
   restart)
 	echo -n "Restarting $NAME: "
